import Foundation
import simd

// ============================================================================
//  test_bindu_noise.swift — parity gate for the Metal noise port.
//
//  The orb's whole look rides on snoise()/fbm(). This test ports the SAME
//  algorithm to Swift/simd and asserts it reproduces reference values captured
//  from the SOURCE OF TRUTH GLSL (src/lib/binduShaders.mjs NOISE block) — so we
//  KNOW the Metal translation in Bindu/Shaders.metal is faithful, not just that
//  it compiles. (The Swift here mirrors the MSL line-for-line; they share one
//  algorithm, so a Swift pass implies the MSL math is correct.)
//
//  Reference values were generated by running the exact GLSL snoise/fbm in JS
//  (/tmp/snoise_ref.mjs) — see the FIXTURES below.
//
//  Run:  cd ios/App/App/Native/Bindu && swift test_bindu_noise.swift
//  Exit 0 = parity holds.  Non-zero = drift; do NOT ship.
// ============================================================================

// MARK: - Swift port (mirrors Bindu/Shaders.metal snoise/fbm exactly)

private func mod289(_ x: SIMD3<Float>) -> SIMD3<Float> { x - floor(x / 289.0) * 289.0 }
private func mod289(_ x: SIMD4<Float>) -> SIMD4<Float> { x - floor(x / 289.0) * 289.0 }
private func permute(_ x: SIMD4<Float>) -> SIMD4<Float> { mod289((x * 34.0 + 1.0) * x) }
private func taylorInvSqrt(_ r: SIMD4<Float>) -> SIMD4<Float> { 1.79284291400159 - 0.85373472095314 * r }

private func snoise(_ v: SIMD3<Float>) -> Float {
    let C = SIMD2<Float>(1.0 / 6.0, 1.0 / 3.0)
    let i  = floor(v + SIMD3<Float>(repeating: simd_dot(v, SIMD3<Float>(repeating: C.y))))
    let x0 = v - i + SIMD3<Float>(repeating: simd_dot(i, SIMD3<Float>(repeating: C.x)))
    // g = step(x0.yzx, x0.xyz)
    let yzx = SIMD3<Float>(x0.y, x0.z, x0.x)
    let g = SIMD3<Float>(yzx.x <= x0.x ? 1 : 0, yzx.y <= x0.y ? 1 : 0, yzx.z <= x0.z ? 1 : 0)
    let l  = SIMD3<Float>(repeating: 1.0) - g
    let lzxy = SIMD3<Float>(l.z, l.x, l.y)
    let i1 = simd_min(g, lzxy)
    let i2 = simd_max(g, lzxy)
    let x1 = x0 - i1 + SIMD3<Float>(repeating: C.x)
    let x2 = x0 - i2 + SIMD3<Float>(repeating: C.y)
    let x3 = x0 - 0.5
    let im = mod289(i)
    let p = permute(permute(permute(
        SIMD4<Float>(im.z + 0.0, im.z + i1.z, im.z + i2.z, im.z + 1.0))
        + SIMD4<Float>(im.y + 0.0, im.y + i1.y, im.y + i2.y, im.y + 1.0))
        + SIMD4<Float>(im.x + 0.0, im.x + i1.x, im.x + i2.x, im.x + 1.0))
    let j  = p - 49.0 * floor(p / 49.0)
    let x_ = floor(j / 7.0)
    let y_ = j - 7.0 * x_
    let x  = x_ / 7.0 + 0.5 / 7.0 - 0.5
    let y  = y_ / 7.0 + 0.5 / 7.0 - 0.5
    let h  = SIMD4<Float>(repeating: 1.0) - abs(x) - abs(y)
    let b0 = SIMD4<Float>(x.x, x.y, y.x, y.y)
    let b1 = SIMD4<Float>(x.z, x.w, y.z, y.w)
    let s0 = floor(b0) * 2.0 + 1.0
    let s1 = floor(b1) * 2.0 + 1.0
    // sh = -step(h, 0) -> -1 where h <= 0 else 0
    let sh = SIMD4<Float>(h.x <= 0 ? -1 : 0, h.y <= 0 ? -1 : 0, h.z <= 0 ? -1 : 0, h.w <= 0 ? -1 : 0)
    // a0 = b0.xzyw + s0.xzyw * sh.xxyy
    let b0xzyw = SIMD4<Float>(b0.x, b0.z, b0.y, b0.w)
    let s0xzyw = SIMD4<Float>(s0.x, s0.z, s0.y, s0.w)
    let shxxyy = SIMD4<Float>(sh.x, sh.x, sh.y, sh.y)
    let a0 = b0xzyw + s0xzyw * shxxyy
    let b1xzyw = SIMD4<Float>(b1.x, b1.z, b1.y, b1.w)
    let s1xzyw = SIMD4<Float>(s1.x, s1.z, s1.y, s1.w)
    let shzzww = SIMD4<Float>(sh.z, sh.z, sh.w, sh.w)
    let a1 = b1xzyw + s1xzyw * shzzww
    var p0 = SIMD3<Float>(a0.x, a0.y, h.x)
    var p1 = SIMD3<Float>(a0.z, a0.w, h.y)
    var p2 = SIMD3<Float>(a1.x, a1.y, h.z)
    var p3 = SIMD3<Float>(a1.z, a1.w, h.w)
    let norm = taylorInvSqrt(SIMD4<Float>(simd_dot(p0, p0), simd_dot(p1, p1), simd_dot(p2, p2), simd_dot(p3, p3)))
    p0 *= norm.x; p1 *= norm.y; p2 *= norm.z; p3 *= norm.w
    var m = simd_max(0.6 - SIMD4<Float>(simd_dot(x0, x0), simd_dot(x1, x1), simd_dot(x2, x2), simd_dot(x3, x3)), SIMD4<Float>(repeating: 0))
    m = m * m
    return 42.0 * simd_dot(m * m, SIMD4<Float>(simd_dot(p0, x0), simd_dot(p1, x1), simd_dot(p2, x2), simd_dot(p3, x3)))
}

private func fbm(_ p: SIMD3<Float>) -> Float {
    0.5 * snoise(p) + 0.25 * snoise(p * 2.03) + 0.125 * snoise(p * 4.01)
}

// MARK: - Fixtures (from /tmp/snoise_ref.mjs over the GLSL source of truth)

struct Fixture { let v: SIMD3<Float>; let snoise: Float; let fbm: Float }

let fixtures: [Fixture] = [
    Fixture(v: SIMD3<Float>(0, 0, 0),                 snoise: -0.52083553, fbm: -0.45573109),
    Fixture(v: SIMD3<Float>(1, 2, 3),                 snoise:  0.71178787, fbm:  0.42304489),
    Fixture(v: SIMD3<Float>(0.5, 0.5, 0.5),           snoise:  0.31995069, fbm:  0.28280706),
    Fixture(v: SIMD3<Float>(2.2, 1.1, 0.20),          snoise:  0.57729762, fbm:  0.18452168),
    Fixture(v: SIMD3<Float>(3.0, 0.075, 0.0),         snoise:  0.24630018, fbm:  0.33367113),
    Fixture(v: SIMD3<Float>(5.0, 0.10, 9.0),          snoise: -0.46511521, fbm: -0.26016399),
    Fixture(v: SIMD3<Float>(20.0, 0.13, 2.0),         snoise:  0.17172059, fbm:  0.15678814),
    Fixture(v: SIMD3<Float>(-1.5, 2.7, 0.4),          snoise:  0.24381495, fbm:  0.01976315),
    Fixture(v: SIMD3<Float>(3.14159, 2.71828, 1.41421), snoise: -0.25417730, fbm: -0.18195072),
]

// MARK: - Run

// float32 simplex noise; tolerance accounts for float32 vs the JS double ref.
let tol: Float = 2e-4
var failures = 0

for (idx, f) in fixtures.enumerated() {
    let gotS = snoise(f.v)
    let gotF = fbm(f.v)
    let dS = abs(gotS - f.snoise)
    let dF = abs(gotF - f.fbm)
    let okS = dS <= tol
    let okF = dF <= tol
    if !okS || !okF { failures += 1 }
    let mark = (okS && okF) ? "ok  " : "FAIL"
    print(String(format: "[%@] #%d v=(%.4f,%.4f,%.4f)  snoise got=%.8f ref=%.8f Δ=%.2e | fbm got=%.8f ref=%.8f Δ=%.2e",
                 mark, idx, f.v.x, f.v.y, f.v.z, gotS, f.snoise, dS, gotF, f.fbm, dF))
}

// Determinism check: same input -> same output (no global state leak).
let detV = SIMD3<Float>(7.0, 1.5, 0.3)
assert(snoise(detV) == snoise(detV), "snoise must be deterministic")

if failures == 0 {
    print("\nPASS — Metal noise port matches the GLSL source of truth (\(fixtures.count) fixtures, tol \(tol)).")
    exit(0)
} else {
    print("\nFAIL — \(failures) fixture(s) drifted from the GLSL reference. Metal orb noise is NOT faithful.")
    exit(1)
}
